# Generated by Django 3.1.1 on 2020-12-18 12:31

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, validators=[customer.models.validate_name])),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[customer.models.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Part Payment', 'Part Payment')], max_length=14, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(to='catalog.Order_Item')),
            ],
        ),
    ]
